### ISSUE TITLE
Good work!

### ISSUE THREAD

**Issue by pyloque** [soulrebel/objproxies#3]
objproxies is a kind of very usefull library,  but the library's name itself sucks!
lot's of people don't know about your library, that's really sad about it.
maybe you should change a good name. It's good for broadcasting, I think.

**Comment by neg3ntropy** [comment]
Thank you!

**Comment by jayvdb** [comment]
Would you mind creating a LICENSE file in this repository?

**Comment by neg3ntropy** [comment]
@jayvdb the license would be Zope Public License or Python Software Foundation License as per the originating source code. I don't really know how to put up a LICENSE file for this situation.

**Comment by jayvdb** [comment]
@neg3ntropy , create a LICENSE file which includes both licenses, and put a short note at the top describing that - "as per the originating source code" is sufficient IMO.  Anyone wanting more clarification knows they need to check the repo.  Then in setup.py `license="ZPL and Python-2.0"` (or other SPDX ids) or `license="Zope and PSF"` (better for humans, not so good for computers).  It is "and" because it is a mix of both, and so the default assumption is that each line must be assumed to be under the terms of both licenses strangely merged together - "and" basically says "not or".

**Comment by neg3ntropy** [comment]
Closing in favor of #5
